version: 2
updates:
  - package-ecosystem: cargo
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
