# Funding and sponsorship

github: [sunormesky-max]
ko_fi: epicode  # Replace with your Ko-fi username or remove if not using
buy_me_a_coffee: epicode  # Replace with your Buy Me a Coffee username or remove if not using
custom:
  - "https://epicode.cn"
