# Funding and sponsorship

# Replace the placeholders below with your real accounts.
# github: [sunormesky-max]
# patreon: # your-patreon-username
# open_collective: # your-open-collective-name
custom:
  - "https://epicode.cn"
  # - "https://afdian.net/@sunormesky"  # 爱发电
