"""Epicode SDK – Python client library."""

from epicode.client import EpicodeClient
from epicode.admin import EpicodeAdmin
from epicode.exceptions import (
    AuthenticationError,
    EpicodeError,
    NotFoundError,
    PlanLimitExceededError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from epicode.models import (
    AdminStatsResponse,
    AdminUsersResponse,
    AskMemory,
    AskResponse,
    CreateNodeResponse,
    DreamCycleResponse,
    Emotion,
    HealthResponse,
    IdentityStepResponse,
    KnowledgeResponse,
    RecallResponse,
    RecallWithTiersResponse,
    RegisterResponse,
    RememberResponse,
    SearchResult,
    SearchResponse,
    SmrpEnvelope,
    SmrpProtocol,
    StatsResponse,
    TimelineEvent,
    TimelineResponse,
    TieredMemoryResult,
)

__version__ = "1.7.0"  # x-release-please-version
__all__ = [
    "EpicodeClient",
    "EpicodeAdmin",
    "EpicodeError",
    "AuthenticationError",
    "NotFoundError",
    "PlanLimitExceededError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    "AdminStatsResponse",
    "AdminUsersResponse",
    "AskMemory",
    "AskResponse",
    "CreateNodeResponse",
    "DreamCycleResponse",
    "Emotion",
    "HealthResponse",
    "IdentityStepResponse",
    "KnowledgeResponse",
    "RecallResponse",
    "RecallWithTiersResponse",
    "RegisterResponse",
    "RememberResponse",
    "SearchResult",
    "SearchResponse",
    "SmrpEnvelope",
    "SmrpProtocol",
    "StatsResponse",
    "TimelineEvent",
    "TimelineResponse",
    "TieredMemoryResult",
]
